//
//  ACSolanaInstructionReturnData.swift
//  AstraConnect
//
//  Created by scott on 2025/10/24.
//

import Foundation

/// The most-recent return data generated by an instruction in the transaction.
public struct ACSolanaInstructionReturnData: Codable {
    
    /// The program that generated the return data, as base-58 encoded Pubkey.
    public var programId: String
    
    /// The return data itself, as base-64 encoded binary data.
    public var data: [String]
    
    /// Creating a instance of InstructionReturnDataw which represents the most-recent return data generated by an instruction in the transaction.
    /// - Parameters:
    ///   - programId: The program that generated the return data, as base-58 encoded Pubkey.
    ///   - data: The return data itself, as base-64 encoded binary data.
    public init(programId: String, data: [String]) {
        self.programId = programId
        self.data = data
    }
}
