//
//  ACSolanasimulationTxInfo.swift
//  AstraConnect
//
//  Created by scott on 2025/11/2.
//

import Foundation

/// A model represents informations about simulated transaction.
public struct ACSolanasimulationTxInfo: Codable, Sendable {
    
    /// Array of accounts with the same length as the accounts.addresses array in the request.
    public var accounts: [ACSolanaAccountInfo]?
    
    /// Error if transaction failed, null if transaction succeeded, may be string or object.
    public var err: ACDynamicCodation?
    
    /// Defined only if innerInstructions was set to true.
    public var innerInstructions: [ACSolanaInnerInstructions]?
    
    /// The number of bytes of all accounts loaded by this transaction.
    public var loadedAccountsDataSize: UInt32?
    
    /// Array of log messages the transaction instructions output during execution, null if simulation failed before the transaction was able to execute.
    public var logs: [String]?
    
    /// The blockhash used to simulate the transaction.
    public var replacementBlockhash: ACSolanaLatestBlockInfo?
    
    /// The most-recent return data generated by an instruction in the transaction.
    public var returnData: ACSolanaInstructionReturnData?
    
    /// The number of compute budget units consumed during the processing of this transaction.
    public var unitsConsumed: UInt64?
    
    /// Array of u64 account balances from before the transaction was processed.
    public var preBalances: [UInt64]?
    
    /// List of token balances from before the transaction was processed or omitted if token balance
    /// recording was not yet enabled during this transaction
    public var preTokenBalances: [ACSolanaTokenBalance]?
    
    /// Array of u64 account balances after the transaction was processed.
    public var postBalances: [UInt64]?
    
    /// List of token balances from after the transaction was processed or omitted if token balance recording
    /// was not yet enabled during this transaction
    public var postTokenBalances: [ACSolanaTokenBalance]?
    
    /// Creating a instance of ACSolanasimulationTxInfo  which represents informations about simulated transaction.
    /// - Parameters:
    ///   - accounts: Array of accounts with the same length as the accounts.addresses array in the request.
    ///   - err: Error if transaction failed, null if transaction succeeded, may be string or object.
    ///   - innerInstructions: Defined only if innerInstructions was set to true.
    ///   - loadedAccountsDataSize: he number of bytes of all accounts loaded by this transaction.
    ///   - logs: Array of log messages the transaction instructions output during execution, null if simulation failed before the transaction was able to execute.
    ///   - replacementBlockhash: The blockhash used to simulate the transaction.
    ///   - returnData: The most-recent return data generated by an instruction in the transaction.
    ///   - unitsConsumed: The number of compute budget units consumed during the processing of this transaction.
    public init(accounts: [ACSolanaAccountInfo]? = nil,
                err: ACDynamicCodation? = nil,
                innerInstructions: [ACSolanaInnerInstructions]? = nil,
                loadedAccountsDataSize: UInt32? = nil,
                logs: [String]? = nil,
                replacementBlockhash: ACSolanaLatestBlockInfo? = nil,
                returnData: ACSolanaInstructionReturnData? = nil,
                unitsConsumed: UInt64? = nil,
                preBalances: [UInt64]? = nil,
                preTokenBalances: [ACSolanaTokenBalance]? = nil,
                postBalances: [UInt64]? = nil,
                postTokenBalances: [ACSolanaTokenBalance]? = nil) {
        self.accounts = accounts
        self.err = err
        self.innerInstructions = innerInstructions
        self.loadedAccountsDataSize = loadedAccountsDataSize
        self.logs = logs
        self.replacementBlockhash = replacementBlockhash
        self.returnData = returnData
        self.unitsConsumed = unitsConsumed
        self.preBalances = preBalances
        self.preTokenBalances = preTokenBalances
        self.postBalances = postBalances
        self.postTokenBalances = postTokenBalances
    }
}
