//
//  ACSolanaTxStatusMetadata.swift
//  AstraConnect
//
//  Created by scott on 2025/10/24.
//


import Foundation

/*
 {
   "meta": {
     "err": null,
     "fee": 5000,
     "innerInstructions": [],
     "logMessages": [],
     "postBalances": [499998932500, 26858640, 1, 1, 1],
     "postTokenBalances": [],
     "preBalances": [499998937500, 26858640, 1, 1, 1],
     "preTokenBalances": [],
     "rewards": null,
     "status": {
       "Ok": null
     }
   }
 }
 */
/// Transaction status metadata, details are shown above. Offical link is:
/// https://solana.com/docs/rpc/json-structures#transaction-status-metadata
public struct ACSolanaTxStatusMetadata: Codable {
    
    /// Error if transaction failed, null if transaction succeeded.
    public var err: ACDynamicCodation
    
    /// Fee this transaction was charged,
    public var fee: UInt64
    
    /// Array of u64 account balances from before the transaction was processed.
    public var preBalances: [UInt64]
    
    /// Array of u64 account balances after the transaction was processed.
    public var postBalances: [UInt64]
    
    /// List of inner instructions or null if inner instruction recording was not enabled during this transaction
    public var innerInstructions: [ACSolanaInnerInstructions]?
    
    /// List of token balances from before the transaction was processed or omitted if token balance
    /// recording was not yet enabled during this transaction
    public var preTokenBalances: [ACSolanaTokenBalance]?
    
    /// List of token balances from after the transaction was processed or omitted if token balance recording
    /// was not yet enabled during this transaction
    public var postTokenBalances: [ACSolanaTokenBalance]?
    
    /// Array of string log messages or null if log message recording was not enabled during this transaction.
    public var logMessages: [String]?
    
    /// Transaction-level rewards; an array of Reward.
    public var rewards: [ACSolanaTxReward]?
    
    /// Transaction addresses loaded from address lookup tables. Undefined if maxSupportedTransactionVersion is not
    /// set in request params, or if jsonParsed encoding is set in request params.
    public var loadedAddresses: ACSolanaLoadedAddresses?
    
    /// The most-recent return data generated by an instruction in the transaction
    public var returnData: ACSolanaInstructionReturnData?
    
    /// Number of compute units consumed by the transaction.
    public var computeUnitsConsumed: UInt64?
    
    /// Transaction version. Undefined if maxSupportedTransactionVersion is not set in request params.
    public var version: ACDynamicCodation?
    
    /// Present if "signatures" are requested for transaction details; an array of signatures strings,
    /// corresponding to the transaction order in the block
    public var signatures: [String]?
    
    /// Creating a instance  of TxStatusMetadata which represents transaction status metadata.
    /// - Parameters:
    ///   - err: Error if transaction failed, null if transaction succeeded
    ///   - fee: Fee this transaction was charged,
    ///   - preBalances: Array of u64 account balances from before the transaction was processed.
    ///   - postBalances: Array of u64 account balances after the transaction was processed.
    ///   - innerInstructions: List of inner instructions or null if inner instruction recording was not enabled during this transaction
    ///   - preTokenBalances: List of token balances from before the transaction was processed or omitted if token balance
    ///   recording was not yet enabled during this transaction
    ///
    ///   - postTokenBalances: List of token balances from after the transaction was processed or omitted if token balance recording
    ///   was not yet enabled during this transaction
    ///
    ///   - logMessages: Array of string log messages or null if log message recording was not enabled during this transaction.
    ///   - rewards: Transaction-level rewards; an array of Reward.
    ///   - loadedAddresses: Transaction addresses loaded from address lookup tables. Undefined if maxSupportedTransactionVersion is not
    ///     set in request params, or if jsonParsed encoding is set in request params.
    ///
    ///   - returnData: The most-recent return data generated by an instruction in the transaction
    ///   - computeUnitsConsumed: Number of compute units consumed by the transaction.
    ///   - version: Transaction version. Undefined if maxSupportedTransactionVersion is not set in request params.
    ///   - signatures: Present if "signatures" are requested for transaction details; an array of signatures strings,
    ///   corresponding to the transaction order in the block
    public init(err: ACDynamicCodation,
                fee: UInt64,
                preBalances: [UInt64],
                postBalances: [UInt64],
                innerInstructions: [ACSolanaInnerInstructions]? = nil,
                preTokenBalances: [ACSolanaTokenBalance]? = nil,
                postTokenBalances: [ACSolanaTokenBalance]? = nil,
                logMessages: [String]? = nil,
                rewards: [ACSolanaTxReward]? = nil,
                loadedAddresses: ACSolanaLoadedAddresses,
                returnData: ACSolanaInstructionReturnData?,
                computeUnitsConsumed: UInt64? = nil,
                version: ACDynamicCodation? = nil,
                signatures: [String]?) {
        self.err = err
        self.fee = fee
        self.preBalances = preBalances
        self.postBalances = postBalances
        self.innerInstructions = innerInstructions
        self.preTokenBalances = preTokenBalances
        self.postTokenBalances = postTokenBalances
        self.logMessages = logMessages
        self.rewards = rewards
        self.loadedAddresses = loadedAddresses
        self.returnData = returnData
        self.computeUnitsConsumed = computeUnitsConsumed
        self.version = version
        self.signatures = signatures
    }
}
